Prueva_DE_SASS/Controllers/MantenimientoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Prueva_DE_SASS.Models;
using Prueva_DE_SASS.Clase;
using System.Data.Entity;

namespace Prueva_DE_SASS.Controllers
{
    public class MantenimientoController : Controller
    {

        // GET: Mantenimiento
        public ActionResult MantenerMuestra()
        {
            try
            {
                using (var conexion = new Servicio_OnlineEntities())
                {


                    var sentencia = from P in conexion.Peliculas
                                    join G in conexion.GeneroPelicula on P.Cod_Genero equals G.Cod_Genero
                                    join I in conexion.Idioma on P.Cod_Idioma equals I.Cod_Idioma orderby P.Cod_Pelicula descending

                                    select new ClsParcialPelicula
                                    {
                                        Cod_Pelicula = P.Cod_Pelicula,
                                        Nombre = P.Nombre,
                                        Actores = P.Actores,
                                        Director = P.Director,
                                        Descripcion = P.Descripcion,
                                        Duracion = P.Duracion,
                                        Precio = P.Precio,
                                        Fecha_Estreno = P.Fecha_Estreno,
                                        Portada = P.Portada,
                                        NombreGeneropelicula = G.Genero,
                                        NombreIdiomapelicula = I.Idioma1

                                    };

                    return View(sentencia.ToList());
                }
            }
            catch (Exception)
            {

                throw;
            }

        }


        /*****************************************METODOS para ingresar*********************************************************************/
        [HttpGet]
        public ActionResult Ingresar()
        {
            ViewBag.Message = ("Estas por ingresar las imagenes");
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Ingresar(ClsParcialPelicula objeto)
        {
            try
            {
                using (var conexion = new Servicio_OnlineEntities())
                {
                    if (!ModelState.IsValid)
                    {
                        
                        var picture = string.Empty;
                        var folder = "~/Content/images/Peliculas";

                        if (objeto.imagefile != null)
                        {
                
                            picture = FileHelpers.UploadPhoto(objeto.imagefile, folder);

                            picture = string.Format("{0}/{1}", folder, picture);

                        }

                        var variable = MetodoPelicula(objeto);

                        variable.Portada = picture;

                        conexion.Peliculas.Add(variable);

                        conexion.SaveChanges();
                        return RedirectToAction("Index");

                    }
                    return View(objeto);
                }


            }
            catch (Exception er)
            {

                ModelState.AddModelError("", "Error al almacenar" + er);
                return View();
            }

        }

        private Peliculas MetodoPelicula(ClsParcialPelicula objeto)
        {
            return new Peliculas
            {
                Cod_Pelicula = objeto.Cod_Pelicula,
                Nombre = objeto.Nombre,
                Actores = objeto.Actores,
                Director = objeto.Director,
                Descripcion = objeto.Descripcion,
                Duracion = objeto.Duracion,
                Precio = objeto.Precio,
                Fecha_Estreno = objeto.Fecha_Estreno,
                Portada = objeto.Portada,
                Cod_Genero = objeto.Cod_Genero,

                Cod_Idioma = objeto.Cod_Idioma



            };
        }
  
        [HttpGet]
        //aqui este recibira un parametro que es el Cod_Pelicula
        public ActionResult Editar(int Cod_Pelicula)
        {
            using (var conexion = new Servicio_OnlineEntities())
            {

                try
                {
                    var objpelicula = conexion.Peliculas.Find(Cod_Pelicula);


                    return View(miotrometodo(objpelicula));

                }
                catch (Exception)
                {

                    ModelState.AddModelError("", "Lo sentimos no se realizo la modificacion que esperaba");
                    return View();
                }
            }

        }

        private ClsParcialPelicula miotrometodo(Peliculas objpelicula)
        {
            return new ClsParcialPelicula
            {

                Cod_Pelicula = objpelicula.Cod_Pelicula,
                Nombre = objpelicula.Nombre,
                Actores = objpelicula.Actores,
                Director = objpelicula.Director,
                Descripcion = objpelicula.Descripcion,
                Duracion = objpelicula.Duracion,
                Precio = objpelicula.Precio,
                Fecha_Estreno = objpelicula.Fecha_Estreno,
                Portada = objpelicula.Portada,
                Cod_Genero = objpelicula.Cod_Genero,
                Cod_Idioma = objpelicula.Cod_Idioma


            };
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Editar(ClsParcialPelicula objpelicula)
        {
            try
            {
                using (var conexion = new Servicio_OnlineEntities())
                {
                    //aqui siempre validamos que siempre el formulaio no tenga campos vacios 
                    if (ModelState.IsValid)
                    {

                        //en este caso inicialisamos la la variable picture no como vacia sino con lo que trae (la imagen que se le ingreso) ya que se esta editando
                        //por logica trae una imagen y sie el usuario no cambia la imagen pues siempre la tendra 
                        var picture = objpelicula.Portada;
                        var folder = "~/Content/images/Peliculas";

                        //aqui en el if validamos que el usuario no  cambio la foto pues siempre la tendra la q tenia anteriormente(el upload esta bacio)
                        if (objpelicula.imagefile != null)
                        {
                            // pero si la cambio me subira la foto
                            picture = FileHelpers.UploadPhoto(objpelicula.imagefile, folder);

                            //y aqui en este ultimo picture me debuelve el nombre de la imagen y con su extencion y ete nombre me lo concatena con 
                            //el nombre de la carpeta Content mas el nombre de la carpeta en donde estara la imagen subida
                            picture = string.Format("{0}/{1}", folder, picture);

                        }



                        var mivariable = MetodoPelicula(objpelicula);

                        //ya que todo estaben mi variable  le asigno lo que tiene el  MetodoPelicula 
                        mivariable.Portada = picture;

                        //pues aqui realisamos el cambio dela imagen biej ala imagen nueva  
                        conexion.Entry(mivariable).State = EntityState.Modified;
                        //aqui guardamos todo en la base de datos 
                        conexion.SaveChanges();
                        return RedirectToAction("Index");
                    }

                    return View(objpelicula);
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Lo sentimos no se realizo la modificacion que esperaba");
                return View();
            }


        }
        /**********************************************************************************************************************************/



        /**********************************************METODO PARA Observar los detalles************************************************************************************/

        public ActionResult Detalles(int Cod_Pelicula)
        {
            try
            {
                using (var conexion = new Servicio_OnlineEntities())
                {

                    var objpelicula = conexion.Peliculas.Find(Cod_Pelicula);

                    if (objpelicula == null)
                    {
                        return HttpNotFound();
                    }
                    else
                    {
                        return View(objpelicula);

                    }

                }


            }
            catch (Exception)
            {

                ModelState.AddModelError("", "Error al solicitar detalles");
                return View();
            }

        }
        /**********************************************************************************************************************************/

        /***************************************** Metodo para Eliminar los registros ****************************************************************/


        public ActionResult Eliminar(int Cod_Pelicula)
        {
            try
            {
                using (var objconexion = new Servicio_OnlineEntities())
                {
                    var obj = objconexion.Peliculas.Find(Cod_Pelicula);
                    objconexion.Peliculas.Remove(obj);
                    objconexion.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {

                ModelState.AddModelError("", "No se realizo la eliminacion del archivo");
                return View();
            }

        }

Prueva_DE_SASS/Views/Mantenimiento/Detalles.cshtml
@model Prueva_DE_SASS.Models.Peliculas

@{
    ViewBag.Title = "Detalles";
}
<h2>Detalles</h2>
<h4>Peliculas</h4>
<hr />
<dl class="dl-horizontal container">
    <dt>
        Titulo
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Nombre)
    </dd>

    <dt>
        Actores
    </dt>

    <dd>
        <div class="panel panel-default">

            @Html.DisplayFor(model => model.Actores)
        </div>
    </dd>
   
    <dt>
        Director
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Director)

    </dd>
  
    <dt>
        Descripción
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Descripcion)
    </dd>


    <dd>

        <table class="table">


            <tr>
                <th>Tiempo de duracion </th>
                <th>Precio de alquiler </th>
                <th>Fecha en que se estreno </th>
                <th>Imagen </th>
                <th> Genero </th>
                <th>Idioma</th>

            </tr>

            <tr>
                <td>
                    @Html.DisplayFor(model => model.Duracion)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Precio)

                </td>

                <td>
                    @Html.DisplayFor(model => model.Fecha_Estreno)
                </td>
                <td>
                    <div class="tamano">
                        @if (!string.IsNullOrEmpty(Model.Portada))
                        {
                            <img src="@Url.Content(Model.Portada)" alt="imagen" />
                        }
                    </div>
                </td>
                <td>
                    @Prueva_DE_SASS.Clase.Class1.mostrargenero(Model.Cod_Genero)
                </td>
                <td>

                    @Prueva_DE_SASS.Clase.Class1.mostraridioma(Model.Cod_Idioma)

                </td>

            </tr>

        </table>
    </dd>
</dl>
<hr />
<p>
    @Html.ActionLink("Editar", "Editar", new { Cod_Pelicula = Model.Cod_Pelicula })
    @Html.ActionLink("Atras", "Index")
</p>

Prueva_DE_SASS/Views/Mantenimiento/Editar.cshtml
@model Prueva_DE_SASS.Models.ClsParcialPelicula

@{
    ViewBag.Title = "Editar";
}

@*<h2>Editar</h2>*@

@using (Html.BeginForm("Editar", "Mantenimiento", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="container contenedorfromulario">


            <h4>Peliculas</h4>
            <hr />
            <div class="tamanodeedicion">

                @*//en esta linea del if mostramos nuestra imagen*@

                @if (!string.IsNullOrEmpty(Model.Portada))
                {
                    <img src="@Url.Content(Model.Portada)" alt="imagen" />
                }

                @*aqui en el HiddenFor le desimos anuestro file upload que si la persona no cambia la imagen el imageload se mantendra *@
                @Html.HiddenFor(model => model.Portada)

            </div>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Cod_Pelicula)
          



            <div class="ladoizquierdo">


                <div class="form-group moverprimerlinea">
                    @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group moverprimerlinea">
                    @Html.LabelFor(model => model.Actores, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Actores, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Actores, "", new { @class = "text-danger" })
                    </div>
                </div>
                <hr class="nad" />
                <div class="form-group moverprimerlinea">
                    @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group moverprimerlinea">
                    @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                    </div>
                </div>
                <hr class="nad" />
                <div class="form-group moverprimerlinea">
                    @Html.LabelFor(model => model.Duracion, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Duracion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Duracion, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group moverprimerlinea">
                    @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label " })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
                    </div>
                </div>
                <hr class="nad" />
                <div class="form-group moverprimerlinea">
                    @Html.LabelFor(model => model.Fecha_Estreno, htmlAttributes: new { @class = "control-label " })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Fecha_Estreno, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Fecha_Estreno, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group moverprimerlinea">
                    @Html.LabelFor(model => model.imagefile, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        <span class="btn btn-default btn-file">

                            @Html.TextBoxFor(modelo => modelo.imagefile, new { Type = "file" })

                        </span>

                        @Html.ValidationMessageFor(model => model.imagefile, "", new { @class = "text-danger" })
                    </div>
                </div>
                <hr class="nad" />
                <div class="form-group moverprimerlinea">
                    @Html.LabelFor(model => model.Cod_Genero, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.Action("ListarGeneroPelicula", "ListarGeneros")

                        @Html.ValidationMessageFor(model => model.Cod_Genero, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group moverprimerlinea">
                    @Html.LabelFor(model => model.Cod_Idioma, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.Action("listarIdiomaspeliculas", "ListarGeneros")
                        @Html.ValidationMessageFor(model => model.Cod_Idioma, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group guardarEditar">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Guardar" class="btn btn-default" />
                    </div>
                    <div class="guardarEditar">
                        @Html.ActionLink("Atras", "Index")
                    </div>


                </div>
            </div>

        </div>

    </div>
}


@section Scripts{


    @Scripts.Render("~/bundles/jqueryval")

    <script>

            $("#Cod_Genero").val('@Model.Cod_Genero');
             $("#Cod_Idioma").val('@Model.Cod_Idioma');

    </script>

}

Prueva_DE_SASS/Views/Mantenimiento/Index.cshtml
@model IEnumerable<Prueva_DE_SASS.Models.Peliculas>
<br />

@using (Html.BeginForm("Index", "Mantenimiento", FormMethod.Get))
{

    <div class="contenedorestatico">
        <div class="mibotonbuscar">
            @Html.TextBox("searching")
            <input type="submit" value="Buscar" class="botonbuscar" />
        </div>
        <div class="mibotonbuscar">
            <a class="btn btn btn-primary" href="/Mantenimiento/Ingresar">Añadir Pelicula <span class="glyphicon glyphicon-plus"></span></a>
        </div>

    </div>

}
<h4>Peliculas</h4>
<br />
@Html.ActionLink("Peliculas de Accion","Accion","Peliculas")
<table class="table table-striped">

    <thead>
        <tr>
            <th>
                Codigo
            </th>
            <th>
                Titulo
            </th>
            @*<th>
                    Actores
                </th>*@
            <th>
                Director
            </th>
            <th>
                Descripcion
            </th>
            <th>
                Duracion/Min
            </th>
            <th>
                Precio
            </th>
            <th>
                Fecha De Estreno
            </th>
            <th>
                Portada
            </th>
            <th>
                Genero
            </th>
            <th>
                Idioma
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>

        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="3" style="color:red">

                    No se encontro lo que buscaba
                </td>

            </tr>

        }
        else
        {

            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cod_Pelicula)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    @*<td>
                                @Html.DisplayFor(modelItem => item.Actores)

                        </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.Director)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Duracion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Precio)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Fecha_Estreno)
                    </td>
                    <td>
                        <div class="tamano">
                            @if (!string.IsNullOrEmpty(item.Portada))
                            {
                                <img src="@Url.Content(item.Portada)" alt="imagen" />
                            }
                        </div>
                    </td>
                    <td>
                        @Prueva_DE_SASS.Clase.Class1.mostrargenero(item.Cod_Genero)

                    </td>
                    <td>
                        @Prueva_DE_SASS.Clase.Class1.mostraridioma(item.Cod_Idioma)

                    </td>
                    <td>
                        <div class="botonesabajo">

                            <div class="botonesabajo">

                                @Html.ActionLink("Editar", "Editar", new { Cod_Pelicula = item.Cod_Pelicula }, new { @class = "btn btn-success miboton" })
                            </div>
                            <div class="botonesabajo">

                                @Html.ActionLink("Detalles", "Detalles", new { Cod_Pelicula = item.Cod_Pelicula }, new { @class = "btn btn-info " })
                            </div>
                            <div class="botonesabajo">
                                @Html.ActionLink("Eliminar", "Eliminar", new { Cod_Pelicula = item.Cod_Pelicula }, new { @class = "btn btn-danger aEliminar" })
                            </div>

                        </div>

                    </td>

                </tr>
            }
        }
    </tbody>
</table>

@section Scripts{

    <script>
        $(".aEliminar").click(function (Event) {
            if (!confirm('Esta seguro de eliminar el registro?')) {

                event.preventDefault();
            }
        });
    </script>
}

Prueva_DE_SASS/Views/Mantenimiento/Ingresar.cshtml
@model Prueva_DE_SASS.Models.ClsParcialPelicula

@{
    ViewBag.Title = "Ingresar";
}

<h2>Ingresar</h2>


@using (Html.BeginForm("Ingresar", "Mantenimiento", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <h4>Peliculas</h4>
    <hr />
    <br />
    <div class="contenedoringresar">

        <div class="form-horizontal">

            <div class="container contenedorfromulario">

                <div class="ladoizquierdo">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Actores, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Actores, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Actores, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <hr class="nad" />

                    <div class="form-group">
                        @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <hr class="nad" />
                    <div class="form-group">
                        @Html.LabelFor(model => model.Duracion, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Duracion, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Duracion, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <hr class="nad" />

                    <div class="form-group">
                        @Html.LabelFor(model => model.Fecha_Estreno, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Fecha_Estreno, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Fecha_Estreno, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.imagefile, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10">
                            @*@Html.EditorFor(model => model.imagefile, new { htmlAttributes = new { @class = "form-control" } })*@

                            <span class="btn btn-default btn-file">

                                @Html.TextBoxFor(modelo => modelo.imagefile, new { Type = "file" })

                            </span>

                            @Html.ValidationMessageFor(model => model.imagefile, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <hr class="nad" />

                    <div class="form-group">
                        @Html.LabelFor(model => model.Cod_Genero, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10">
                            @Html.Action("ListarGeneroPelicula", "ListarGeneros")
                            @Html.ValidationMessageFor(model => model.Cod_Genero, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Cod_Idioma, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10">
                            @*@Html.EditorFor(model => model.Cod_Idioma, new { htmlAttributes = new { @class = "form-control" } })*@
                            @Html.Action("listarIdiomaspeliculas", "ListarGeneros")
                            @Html.ValidationMessageFor(model => model.Cod_Idioma, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <hr class="nad" />
                    <div class="form-group guardarEditar">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Crear" class="btn btn-default tuboton" />
                        </div>

                        <div class="yourboton">
                            @*@Html.ActionLink("Atras", "Index", new { @class = "miboton" })*@
                            <a href="/Mantenimiento/Index" class=" btn btn-default  yourboton">Atras</a>
                        </div>

                    </div>

                </div>

            </div>

        </div>
    </div>


}




@section Scripts {



    @Scripts.Render("~/bundles/jqueryval")


}

Prueva_DE_SASS/Views/Mantenimiento/listargeneropeliculas.cshtml
@model IEnumerable<Prueva_DE_SASS.Models.GeneroPelicula>


@*
    NOTA
    al select le colocamos un id con el mnombre de mi campo q hace la relacion entre las dos tablas en este caso es" Cod_Genero "
    si no le ponemos el msmo nombre no nos reconocera y no nos listara los datos de la tabla GeneroPelicula
 *@
<select class="form-control" id="Cod_Genero" name=" Cod_Genero">

    @foreach (var item in Model)
    {


        //usamos codogo raizor para listar todos los generos que estan alojados ne mi tabla GeneroPelicula
        //tambien

        //Nota  con el @item.Cod_Genero enviara el codigo y CON EL @item.Genero Nos mostrara el nombre 
        <option value="@item.Cod_Genero"> @item.Genero</option>
    }


</select>