Prueva_DE_SASS/Controllers/MantenimientoVideoController.cs
using Prueva_DE_SASS.Clase;
using Prueva_DE_SASS.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Prueva_DE_SASS.Controllers
{
    public class MantenimientoVideoController : Controller
    {
        // GET: MantenimientoVideo
        public ActionResult IndexVideo(string searching)
        {
            using (var conexion = new Servicio_OnlineEntities())
            {
                return View(conexion.Videos.Where(a => a.Nombre.Contains(searching) || searching == null).ToList());


                //en este con starswidhtle indicamos q nos muestre por el primer letra q
                //    ingresamos si ingresamos batman me mostrara solo os q empiesen  con b en cambio
                //con el .Contains nos mostraria todos los que poseen b
                //return View(conexion.Peliculas.Where(a => a.Nombre.StartsWith(searching) || searching == null).ToList());

            }



    }


        /***********************************Este metodo es para Agregar ala base de datos********************/
        [HttpGet]
        public ActionResult AgregarVideo()
        {
            return View();
        }


        [ValidateAntiForgeryToken]//este codigo se encarga que la informcion llegue al formulario correcto
        [HttpPost]
        public ActionResult AgregarVideo(ClsParcialVideo objeto )
        {
            try
            {
                using (var conexion = new Servicio_OnlineEntities())
                {
                    if (!ModelState.IsValid)
                    {
                        //inicialisamos una variable picture para q este vacia
                        var picture = string.Empty;
                        var folder = "~/Content/images/Video";

                        //aqui en el if validamos que el usuario si selecciono una foto en el upload(si hay foto)
                        if (objeto.imagefile != null)
                        {
                            //aqui le desimos ala primera picture que me suba la foto que esta en mi imagefile
                            picture = FileHelpers.UploadPhoto(objeto.imagefile, folder);

                            //y aqui en este ultimo picture me debuelve el nombre de la imagen y con su extencion y ete nombre me lo concatena con 
                            //el nombre de la carpeta Content mas el nombre de la carpeta en donde estara la imagen subida
                            picture = string.Format("{0}/{1}", folder, picture);

                        }

                        var variable = MetodoVideo(objeto);

                        //ya que todo estaben mi variable  le asigno lo que tiene el  MetodoPelicula 
                        variable.Portada = picture;

                        conexion.Videos.Add(variable);
                        //aqui guardamos todo en la base de datos 
                        conexion.SaveChanges();
                        return RedirectToAction("IndexVideo");

                    }
                    return View(objeto);
                }
            }
            catch (Exception er)
            {

                ModelState.AddModelError("", "Error al almacenar" + er);
                return View();
            }
        }



        //este metodo me convertira la imagen 
        private Videos MetodoVideo(ClsParcialVideo objeto1)
        {
            return new Videos
            {
                Cod_Video = objeto1.Cod_Video,
                Nombre = objeto1.Nombre,
                Artista = objeto1.Artista,
                Duracion = objeto1.Duracion,
                Fecha_Estreno = objeto1.Fecha_Estreno,
                Precio =Convert.ToDecimal(objeto1.Precio),
                Portada = objeto1.Portada,
                Cod_Genero=objeto1.Cod_Genero,
                Cod_Idioma = objeto1.Cod_Idioma


            };
        }



        /**************************************************************************************************/


        /********************************************************metodo para Editar********************************************************************/
        public ActionResult EditarVideo(int Cod_Video)
        {
            using (var conexion = new Servicio_OnlineEntities())
            {

                try
                {
                    //validamos q nuestra codigo no sea nullo o mas bien dicho que exista 
                    //if (Cod_Pelicula==null)
                    //{
                    //    return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);

                    //}

                    var objvideo2 = conexion.Videos.Find(Cod_Video);

                    //validamos que lo q tiene mi variable objpelicula tiene algun valor 
                    //if (objpelicula==null)
                    //{
                    //    return HttpNotFound();
                    //}

                    return View(miotrometodoVideo(objvideo2));

                }
                catch (Exception)
                {

                    ModelState.AddModelError("", "Lo sentimos no se realizo la modificacion que esperaba");
                    return View();
                }
            }
        }

        private ClsParcialVideo miotrometodoVideo(Videos objvideo2)
        {
            return new ClsParcialVideo
            {

                Cod_Video = objvideo2.Cod_Video,
                Nombre = objvideo2.Nombre,
                Artista = objvideo2.Artista,
                Duracion = objvideo2.Duracion,
                Fecha_Estreno = objvideo2.Fecha_Estreno,
                Precio = objvideo2.Precio,
                Portada = objvideo2.Portada,
                Cod_Genero = objvideo2.Cod_Genero,
                Cod_Idioma = objvideo2.Cod_Idioma

            };
        }
        



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarVideo(ClsParcialVideo objetovideo)
        {
            try
            {
                using (var conexion = new Servicio_OnlineEntities())
                {
                    //aqui siempre validamos que siempre el formulaio no tenga campos vacios 
                    if (ModelState.IsValid)
                    {

                        //en este caso inicialisamos la la variable picture no como vacia sino con lo que trae (la imagen que se le ingreso) ya que se esta editando
                        //por logica trae una imagen y sie el usuario no cambia la imagen pues siempre la tendra 
                        var picture = objetovideo.Portada;
                        var folder = "~/Content/images/Video";

                        //aqui en el if validamos que el usuario no  cambio la foto pues siempre la tendra la q tenia anteriormente(el upload esta bacio)
                        if (objetovideo.imagefile != null)
                        {
                            // pero si la cambio me subira la foto
                            picture = FileHelpers.UploadPhoto(objetovideo.imagefile, folder);

                            //y aqui en este ultimo picture me debuelve el nombre de la imagen y con su extencion y ete nombre me lo concatena con 
                            //el nombre de la carpeta Content mas el nombre de la carpeta en donde estara la imagen subida
                            picture = string.Format("{0}/{1}", folder, picture);

                        }



                        var mivariable = MetodoVideo(objetovideo);

                        //ya que todo estaben mi variable  le asigno lo que tiene el  MetodoPelicula 
                        mivariable.Portada = picture;

                        //pues aqui realisamos el cambio dela imagen biej ala imagen nueva  
                        conexion.Entry(mivariable).State = EntityState.Modified;
                        //aqui guardamos todo en la base de datos 
                        conexion.SaveChanges();
                        return RedirectToAction("IndexVideo");
                    }

                    return View(objetovideo);
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Lo sentimos no se realizo la modificacion que esperaba");
                return View();
            }
        }

        /**************************************************************************************************************************/





        /******************************************Metodo para Detalles **********************************************************************/

        public ActionResult DetallesVideo(int Cod_Video)
        {
            try
            {
                using (var conexion = new Servicio_OnlineEntities())
                {

                    var objvideo3 = conexion.Videos.Find(Cod_Video);

                    if (objvideo3 == null)
                    {
                        return HttpNotFound();
                    }
                    else
                    {
                        return View(objvideo3);
                    }
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Error al solicitar detalles");
                return View();
            }


        }


        /**************************************************************************************************************************/


        /******************************************Metodo para Eliminar **********************************************************************/
         public ActionResult EliminarVideo(int Cod_Video)
        {
            try
            {
                using (var objconexion = new Servicio_OnlineEntities())
                {
                    var obj = objconexion.Videos.Find(Cod_Video);
                    objconexion.Videos.Remove(obj);
                    objconexion.SaveChanges();

Prueva_DE_SASS/Views/MantenimientoVideo/AgregarVideo.cshtml
@model Prueva_DE_SASS.Models.ClsParcialVideo

@{
    ViewBag.Title = "Ingresar";
}

<h2>Ingresar</h2>

@using (Html.BeginForm("AgregarVideo", "MantenimientoVideo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <h4>Video</h4>
    <hr />
    <br />

    <div class="contenedoringresar">

        <div class="form-horizontal">

            <div class="container contenedorfromulario">

                <div class="ladoizquierdo">

                    <div class="form-group">
                        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Artista, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Artista, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Artista, "", new { @class = "text-danger" })
                        </div>
                    </div>



                    <hr class="nad" />

                    <div class="form-group">
                        @Html.LabelFor(model => model.Duracion, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Duracion, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Duracion, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Fecha_Estreno, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Fecha_Estreno, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Fecha_Estreno, "", new { @class = "text-danger" })
                        </div>
                    </div>



                    <hr class="nad" />

                    <div class="form-group">
                        @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.imagefile, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10">

                            <span class="btn btn-default btn-file">

                                @Html.TextBoxFor(modelo => modelo.imagefile, new { Type = "file" })

                            </span>

                            @Html.ValidationMessageFor(model => model.imagefile, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <hr class="nad" />

                    <div class="form-group">
                        @Html.LabelFor(model => model.Cod_Genero, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10">
                            @Html.Action("ListarGeneroVideo_Musica", "ListarGeneros")
                            @Html.ValidationMessageFor(model => model.Cod_Genero, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Cod_Idioma, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10">

                            @Html.Action("listarIdiomaspeliculas", "ListarGeneros")
                            @Html.ValidationMessageFor(model => model.Cod_Idioma, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <hr class="nad" />

                    <div class="form-group guardarEditar">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Crear" class="btn btn-default tuboton" />
                        </div>
                        @*<div>
                            @Html.ActionLink("Atras", "IndexVideo")
                        </div>*@

                        <div class="yourboton">

                            <a href="/MantenimientoVideo/IndexVideo" class=" btn btn-default  yourboton">Atras</a>
                        </div>

                    </div>

                </div>
            </div>
        </div>


    </div>


}

Prueva_DE_SASS/Views/MantenimientoVideo/DetallesVideo.cshtml
@model Prueva_DE_SASS.Models.Videos

@{
    ViewBag.Title = "DetallesVideo";
}

<h2>Detalles</h2>
<h4>@Model.Nombre</h4>
<hr />
<dl class="dl-horizontal container">

    <dt>
        Titulo

    </dt>
    <dd>
        <div class="panel panel-default">
            @Html.DisplayFor(model => model.Nombre)
        </div>
    </dd>

    <dt>
        Artista
    </dt>

    <dd>
        <div class="panel panel-default">

            @Html.DisplayFor(model => model.Artista)
        </div>
    </dd>


    <dd>

        <table class="table">


            <tr>
                <th>Tiempo de duracion </th>
                <th>Fecha en que se estreno </th>
                <th>Precio de alquiler </th>

                <th>Imagen </th>
                <th> Genero </th>
                <th>Idioma</th>

            </tr>

            <tr>
                <td>
                    @Html.DisplayFor(model => model.Duracion)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Fecha_Estreno)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Precio)

                </td>

                <td>
                    <div class="tamano">
                        @if (!string.IsNullOrEmpty(Model.Portada))
                        {
                            <img src="@Url.Content(Model.Portada)" alt="imagen" />
                        }
                    </div>
                </td>
                <td>
                    @Prueva_DE_SASS.Clase.Class1.generoMusicVideo(Model.Cod_Genero)
                </td>
                <td>

                    @Prueva_DE_SASS.Clase.Class1.mostraridioma(Model.Cod_Idioma)

                </td>

            </tr>

        </table>
    </dd>
</dl>
<hr />
<p>
    @Html.ActionLink("Editar", "EditarVideo", new { Cod_Video= Model.Cod_Video})
    @Html.ActionLink("Atras", "IndexVideo")
</p>

Prueva_DE_SASS/Views/MantenimientoVideo/EditarVideo.cshtml
@model Prueva_DE_SASS.Models.ClsParcialVideo

@{
    ViewBag.Title = "EditarVideo";
}

<h4>Editar  @Model.Nombre </h4>


@using (Html.BeginForm("EditarVideo", "MantenimientoVideo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="container contenedorfromulario">
            <hr />
            <div class="tamanodeedicion">

                @*//en esta linea del if mostramos nuestra imagen*@

                @if (!string.IsNullOrEmpty(Model.Portada))
                {
                    <img src="@Url.Content(Model.Portada)" alt="imagen" />
                }

                @*aqui en el HiddenFor le desimos anuestro file upload que si la persona no cambia la imagen el imageload se mantendra *@
                @Html.HiddenFor(model => model.Portada)

            </div>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Cod_Video)

            <div class="ladoizquierdo">


                <div class="form-group moverprimerlinea">
                    @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group moverprimerlinea">
                    @Html.LabelFor(model => model.Artista, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Artista, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Artista, "", new { @class = "text-danger" })
                    </div>
                </div>
                <hr class="nad" />
                <div class="form-group moverprimerlinea">
                    @Html.LabelFor(model => model.Duracion, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Duracion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Duracion, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group moverprimerlinea">
                    @Html.LabelFor(model => model.Fecha_Estreno, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Fecha_Estreno, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Fecha_Estreno, "", new { @class = "text-danger" })
                    </div>
                </div>
                <hr class="nad" />

                <div class="form-group moverprimerlinea">
                    @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label " })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group moverprimerlinea">
                    @Html.LabelFor(model => model.imagefile, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        <span class="btn btn-default btn-file">

                            @Html.TextBoxFor(modelo => modelo.imagefile, new { Type = "file" })

                        </span>

                        @Html.ValidationMessageFor(model => model.imagefile, "", new { @class = "text-danger" })
                    </div>
                </div>
                <hr class="nad" />

                <div class="form-group moverprimerlinea">
                    @Html.LabelFor(model => model.Cod_Genero, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.Action("ListarGeneroVideo_Musica", "ListarGeneros")

                        @Html.ValidationMessageFor(model => model.Cod_Genero, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group moverprimerlinea">
                    @Html.LabelFor(model => model.Cod_Idioma, htmlAttributes: new { @class = "control-label" })
                    <div class="col-md-10">
                        @Html.Action("listarIdiomaspeliculas", "ListarGeneros")
                        @Html.ValidationMessageFor(model => model.Cod_Idioma, "", new { @class = "text-danger" })
                    </div>
                </div>
                <hr class="nad" />
                <div class="form-group guardarEditar">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Guardar" class="btn btn-default" />
                    </div>
                    <div class="guardarEditar">
                        @Html.ActionLink("Atras", "IndexVideo")
                    </div>


                </div>
            </div>

        </div>

    </div>

}


@section Scripts{


    @Scripts.Render("~/bundles/jqueryval")

    <script>

            $("#Cod_Genero").val('@Model.Cod_Genero');
             $("#Cod_Idioma").val('@Model.Cod_Idioma');

    </script>

}

Prueva_DE_SASS/Views/MantenimientoVideo/EliminarVideo.cshtml
@model Prueva_DE_SASS.Models.Videos

@{
    ViewBag.Title = "EliminarVideo";
}

<h2>EliminarVideo</h2>

Prueva_DE_SASS/Views/MantenimientoVideo/IndexVideo.cshtml
@model IEnumerable<Prueva_DE_SASS.Models.Videos>
<br />
@using (Html.BeginForm("IndexVideo", "MantenimientoVideo", FormMethod.Get))
{
    <div class="contenedorestatico">


        <div class="mibotonbuscar">
            @Html.TextBox("searching")
            <input type="submit" value="Buscar" class="botonbuscar" />
        </div>
        <div class="mibotonbuscar">
            <a class="btn btn-primary " href="/MantenimientoVideo/AgregarVideo">Añadir Video <span class="glyphicon glyphicon-plus"></span></a>
        </div>

    </div>
}
<h4>Videos</h4>
<br />
<table class="table table-striped">

    <thead>
        <tr>
            <th>
                Codigo
            </th>
            <th>
                Titulo
            </th>

            <th>
                Artistas
            </th>

            <th>
                Duracion/Min
            </th>

            <th>
                Fecha De Estreno
            </th>
            <th>
                Precio
            </th>
            <th>
                Portada
            </th>
            <th>
                Genero
            </th>
            <th>
                Idioma
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>

        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="3" style="color:red">

                    No se encontro la Mausica que solicito!!!
                </td>

            </tr>

        }
        else
        {

            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cod_Video)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    @*<td>
                                @Html.DisplayFor(modelItem => item.Actores)

                        </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.Artista)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Duracion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Fecha_Estreno)
                    </td>



                    <td>
                        @Html.DisplayFor(modelItem => item.Precio)
                    </td>

                    <td>
                        <div class="tamano">
                            @if (!string.IsNullOrEmpty(item.Portada))
                            {
                                <img src="@Url.Content(item.Portada)" alt="imagen" />
                            }
                        </div>
                    </td>
                    <td>
                        @Prueva_DE_SASS.Clase.Class1.generoMusicVideo(item.Cod_Genero)

                    </td>
                    <td>

                        @Prueva_DE_SASS.Clase.Class1.mostraridioma(item.Cod_Idioma)
                    </td>
                    <td>
                        <div class="botonesabajo">

                            <div class="botonesabajo">

                                @Html.ActionLink("Editar", "EditarVideo", new { Cod_Video = item.Cod_Video }, new { @class = "btn btn-success miboton" })
                            </div>
                            <div class="botonesabajo">

                                @Html.ActionLink("Detalles", "DetallesVideo", new { Cod_Video = item.Cod_Video }, new { @class = "btn btn-info " })
                            </div>
                            <div class="botonesabajo">
                                @Html.ActionLink("Eliminar", "EliminarVideo", new { Cod_Video = item.Cod_Video }, new { @class = "btn btn-danger aEliminar" })
                            </div>

                        </div>

                    </td>

                </tr>
            }
        }
    </tbody>
</table>

@section Scripts{

    <script>
        $(".aEliminar").click(function (Event) {
            if (!confirm('Esta seguro de eliminar el registro?')) {

                event.preventDefault();
            }
        });
    </script>
}